### ISSUE TITLE
Documentation does not build on main

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/ClimaOcean.jl#134]
Apparently, the documentation does not build on the main, but only on PRs when adding the `Run Example` label.
These are the steps in the buildkite settings
```
steps:
  - command: "buildkite-agent pipeline upload .buildkite/examples_build.yml "
    label: ":pipeline:"
    if: "build.pull_request.labels includes \"Run examples\""
    agents:
      queue: new-central
```
There is the possibility of running the pipeline on a schedule on main, do we want to do it nightly?
