### ISSUE TITLE
Docs built

### ISSUE THREAD

**Issue by navidcy** [CliMA/ClimaOcean.jl#161]
At the moment the docs are build with GitHub actions and also via buildkite-ci for examples.

But we can't have two ways of building the docs. When GitHub actions build docs without the examples then it pushes it and it overwrites the other docs. However the buildkite-CI only runs when the PR has a particular label... 

The workflow is not robust and results in situations like the one described in #157...

**Comment by simone-silvestri** [comment]
I thought that #156 would solve this issue by nuking the GitHub actions build. Note that the docs are build always on main. The steps in buildkite read:
```
steps:
  - command: "buildkite-agent pipeline upload .buildkite/examples_build.yml "
    label: ":pipeline:"
    if: "build.pull_request.labels includes \"Run examples\" || build.branch == \"main\"" 
    agents:
      queue: new-central
```
