### ISSUE TITLE
Daily docs building for `main` fail?

### ISSUE THREAD

**Issue by navidcy** [CliMA/ClimaOcean.jl#497]
@simone-silvestri you had set up a daily build of the docs of main.
Now after #466 our docs pass but we still don't have an updated `dev` doc.

I see the last few daily docs build on main failed. E.g.,
https://buildkite.com/clima/climaocean-examples/builds/3165

Does this have to do anything with @glwagner moving the docs to build on tartarus? Anything else that went astray?

**Comment by glwagner** [comment]
here's the steps from buildkite

```
steps:
  - command: "buildkite-agent pipeline upload .buildkite/examples_build.yml "
    label: ":pipeline:"
    if: "build.pull_request.labels includes \"build docs\" || build.tag != null || (build.branch == 'main' && build.source == 'schedule')"
    agents:
      queue: ClimaOcean-docs
```
